fos_user:
    db_driver:              orm
    firewall_name:          main
    user_class:             AppBundle\Entity\User
    use_listener:           true
    use_flash_notifications: true
    use_username_form_type: true